document.addEventListener('DOMContentLoaded',function(){
/* === Hero mobile bg swap === */
if(window.innerWidth<=768){var heroImg=document.querySelector('.hero-mobile-bg');if(heroImg)heroImg.src='images/mobile/caps-1.webp';}
/* === Vimeo lazy load (desktop only, 6s timeout) === */
var vimeoIframe=document.querySelector('.hero-video-bg iframe[data-src]');if(vimeoIframe&&window.innerWidth>768){var vimeoLoaded=false;function loadVimeo(){if(vimeoLoaded)return;vimeoLoaded=true;vimeoIframe.src=vimeoIframe.getAttribute('data-src');}
var iev=['scroll','mousemove','touchstart','keydown'];function onInt(){loadVimeo();iev.forEach(function(e){window.removeEventListener(e,onInt);});}
iev.forEach(function(e){window.addEventListener(e,onInt,{once:true,passive:true});});setTimeout(loadVimeo,6000);}
/* === Consent (deferred via rIC) === */
var ric=window.requestIdleCallback||function(cb){setTimeout(cb,1);};
ric(function(){
window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}
gtag('consent','default',{'analytics_storage':'denied','ad_storage':'denied','ad_user_data':'denied','ad_personalization':'denied','functionality_storage':'granted','security_storage':'granted'});
var savedChoice=localStorage.getItem('cookie-choice');var savedStats=localStorage.getItem('cookie-stats');
if(savedChoice==='accepted'){var sg=savedStats!=='denied';gtag('consent','update',{'analytics_storage':sg?'granted':'denied','ad_storage':sg?'granted':'denied','ad_user_data':sg?'granted':'denied','ad_personalization':sg?'granted':'denied'});}
window.gtag=gtag;
var cb=document.getElementById('cookie-banner');var ca=document.getElementById('cookie-accept');var cd=document.getElementById('cookie-decline');var cm=document.getElementById('cookie-manage');var cc=document.getElementById('cookie-close');var cp=document.getElementById('cookie-prefs');var cs=document.getElementById('cookie-stats');
if(savedChoice==='accepted'||savedChoice==='declined'){cb.classList.add('dismissed');cb.style.visibility='visible';}else{setTimeout(function(){cb.style.visibility='visible';},1000);}
if(savedStats==='denied'&&cs)cs.checked=false;
function dismiss(ch){cb.classList.add('dismissed');localStorage.setItem('cookie-choice',ch);var sa=cs&&cs.checked;localStorage.setItem('cookie-stats',sa?'granted':'denied');if(ch==='accepted'){gtag('consent','update',{'analytics_storage':sa?'granted':'denied','ad_storage':sa?'granted':'denied','ad_user_data':sa?'granted':'denied','ad_personalization':sa?'granted':'denied'});}else{gtag('consent','update',{'analytics_storage':'denied','ad_storage':'denied','ad_user_data':'denied','ad_personalization':'denied'});}}
ca.addEventListener('click',function(){dismiss('accepted');});cd.addEventListener('click',function(){dismiss('declined');});cc.addEventListener('click',function(){cb.classList.add('dismissed');});cm.addEventListener('click',function(){cp.classList.toggle('hidden');this.textContent=cp.classList.contains('hidden')?'ניהול העדפות':'שמור העדפות';});
});
/* === HubSpot form init === */
var exitShown=false;
function initHSForm(){if(typeof hbspt==='undefined'){window.addEventListener('hsformsready',initHSForm,{once:true});return;}
hbspt.forms.create({region:'eu1',portalId:'143688847',formId:'5acc9316-e04d-4d87-a352-f7cf317c9b62',target:'#hs-lead-form',onFormReady:function($form){document.getElementById('hs-lead-form').classList.add('hs-ready');var ph={'full_name_he':'\u05E9\u05DD \u05DE\u05DC\u05D0','phone':'\u05D8\u05DC\u05E4\u05D5\u05DF','email':'\u05DE\u05D9\u05D9\u05DC'};$form.querySelectorAll('.hs-input').forEach(function(inp){var n=inp.name;if(ph[n])inp.placeholder=ph[n];});var nf=$form.querySelector('.hs_full_name_he');var pf=$form.querySelector('.hs_phone');var ef=$form.querySelector('.hs_email');var con=$form.querySelector('.legal-consent-container');var sub=$form.querySelector('.hs_submit');if(nf)$form.appendChild(nf);if(pf)$form.appendChild(pf);if(ef)$form.appendChild(ef);if(con){var ct=con.querySelector('p');if(ct)ct.textContent='\u05D1\u05DC\u05D7\u05D9\u05E6\u05D4 \u05D0\u05EA/\u05D4 \u05DE\u05D0\u05E9\u05E8/\u05EA \u05DC\u05E7\u05D1\u05DC \u05DE\u05D9\u05D3\u05E2 \u05DE\u05D4\u05DE\u05E8\u05DB\u05D6 \u05D4\u05D0\u05E7\u05D3\u05DE\u05D9 \u05E4\u05E8\u05E1. \u05E0\u05D9\u05EA\u05DF \u05DC\u05D1\u05D8\u05DC \u05D1\u05DB\u05DC \u05E2\u05EA.';$form.appendChild(con);}if(sub)$form.appendChild(sub);var btn=$form.querySelector('.hs-button');if(btn)btn.value='\u2190 \u05EA\u05D7\u05D6\u05E8\u05D5 \u05D0\u05DC\u05D9\u05D9';},onFormSubmit:function($form){$form.style.opacity='0';$form.style.pointerEvents='none';},onFormSubmitted:function(){if(typeof gtag==='function'){gtag('event','generate_lead',{event_category:'form',event_label:'form_complete'});}document.getElementById('hs-lead-form').classList.add('hidden');document.getElementById('form-success').classList.remove('hidden');var b=document.querySelector('.form-badge');var t=document.querySelector('.form-title');if(b)b.classList.add('hidden');if(t)t.classList.add('hidden');exitShown=true;localStorage.setItem('exit-popup-shown','1');}});}
initHSForm();
/* === Carousels (deferred to after paint) === */
requestAnimationFrame(function(){setTimeout(function(){
/* Cert shuffle with DocumentFragment */
var certTrack=document.getElementById('certificates-track');if(certTrack){var certCards=Array.from(certTrack.querySelectorAll('.cert-card'));var frag=document.createDocumentFragment();for(var i=certCards.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var t=certCards[i];certCards[i]=certCards[j];certCards[j]=t;}certCards.forEach(function(c){frag.appendChild(c);});certTrack.appendChild(frag);}
function setupCarouselArrows(tid,rid,lid){var tr=document.getElementById(tid);var rb=document.getElementById(rid);var lb=document.getElementById(lid);if(!tr||!rb||!lb)return;var sa=280;rb.addEventListener('click',function(){if(tr.scrollLeft>=-10){tr.style.scrollBehavior='auto';tr.scrollLeft=-(tr.scrollWidth-tr.clientWidth);tr.style.scrollBehavior='smooth';setTimeout(function(){tr.scrollLeft+=sa;},50);}else{tr.scrollLeft+=sa;}});lb.addEventListener('click',function(){var ms=tr.scrollWidth-tr.clientWidth;if(tr.scrollLeft<=-(ms-10)){tr.style.scrollBehavior='auto';tr.scrollLeft=0;tr.style.scrollBehavior='smooth';setTimeout(function(){tr.scrollLeft-=sa;},50);}else{tr.scrollLeft-=sa;}});}
setupCarouselArrows('certificates-track','cert-arrow-right','cert-arrow-left');setupCarouselArrows('employers-track','emp-arrow-right','emp-arrow-left');setupCarouselArrows('testimonials-track','test-arrow-right','test-arrow-left');
/* Dots with DocumentFragment */
var track=document.getElementById('testimonials-track');var dotsC=document.getElementById('testimonials-dots');var cards=track.querySelectorAll('.testimonial-card');var dc=Math.min(cards.length,6);var dotFrag=document.createDocumentFragment();for(var i=0;i<dc;i++){var dot=document.createElement('span');dot.className='dot'+(i===0?' active':'');dot.dataset.index=i;dot.addEventListener('click',function(){cards[parseInt(this.dataset.index)].scrollIntoView({behavior:'smooth',inline:'start',block:'nearest'});});dotFrag.appendChild(dot);}dotsC.appendChild(dotFrag);
/* Scroll dots - cache cardWidth */
var cachedCardWidth=0;var scrollTimer;track.addEventListener('scroll',function(){clearTimeout(scrollTimer);scrollTimer=setTimeout(function(){var sl=track.scrollLeft;if(!cachedCardWidth)cachedCardWidth=cards[0].offsetWidth+24;var idx=Math.round(Math.abs(sl)/cachedCardWidth);idx=Math.max(0,Math.min(idx,dc-1));dotsC.querySelectorAll('.dot').forEach(function(d,i){d.classList.toggle('active',i===idx);});},150);},{passive:true});
},0);});
/* === Exit popup (deferred) === */
var exitPopup=document.getElementById('exit-popup');var exitOverlay=document.getElementById('exit-overlay');var exitClose=document.getElementById('exit-close');
function showExitPopup(){if(exitShown||localStorage.getItem('exit-popup-shown'))return;exitShown=true;exitPopup.classList.remove('hidden');localStorage.setItem('exit-popup-shown','1');hbspt.forms.create({region:'eu1',portalId:'143688847',formId:'5acc9316-e04d-4d87-a352-f7cf317c9b62',target:'#hs-exit-form',onFormReady:function($form){$form.style.transition='opacity 0.3s';var ph={'full_name_he':'\u05E9\u05DD \u05DE\u05DC\u05D0','phone':'\u05D8\u05DC\u05E4\u05D5\u05DF','email':'\u05DE\u05D9\u05D9\u05DC'};$form.querySelectorAll('.hs-input').forEach(function(inp){var n=inp.name;if(ph[n])inp.placeholder=ph[n];});var nf=$form.querySelector('.hs_full_name_he');var pf=$form.querySelector('.hs_phone');var ef=$form.querySelector('.hs_email');var con=$form.querySelector('.legal-consent-container');var sub=$form.querySelector('.hs_submit');if(nf)$form.appendChild(nf);if(pf)$form.appendChild(pf);if(ef)$form.appendChild(ef);if(con){var ct=con.querySelector('p');if(ct)ct.textContent='\u05D1\u05DC\u05D7\u05D9\u05E6\u05D4 \u05D0\u05EA/\u05D4 \u05DE\u05D0\u05E9\u05E8/\u05EA \u05DC\u05E7\u05D1\u05DC \u05DE\u05D9\u05D3\u05E2 \u05DE\u05D4\u05DE\u05E8\u05DB\u05D6 \u05D4\u05D0\u05E7\u05D3\u05DE\u05D9 \u05E4\u05E8\u05E1. \u05E0\u05D9\u05EA\u05DF \u05DC\u05D1\u05D8\u05DC \u05D1\u05DB\u05DC \u05E2\u05EA.';$form.appendChild(con);}if(sub)$form.appendChild(sub);var btn=$form.querySelector('.hs-button');if(btn)btn.value='\u2190 \u05EA\u05D7\u05D6\u05E8\u05D5 \u05D0\u05DC\u05D9\u05D9';},onFormSubmit:function($form){$form.style.opacity='0';$form.style.pointerEvents='none';},onFormSubmitted:function(){if(typeof gtag==='function')gtag('event','exit_intent_lead',{event_category:'form',event_label:'exit_popup'});document.getElementById('hs-exit-form').classList.add('hidden');document.querySelector('.exit-popup-content h3').classList.add('hidden');document.querySelector('.exit-popup-content p').classList.add('hidden');document.getElementById('exit-success').classList.remove('hidden');setTimeout(closeExitPopup,2500);}});}
function closeExitPopup(){exitPopup.classList.add('hidden');}
document.addEventListener('mouseout',function(e){if(e.clientY<=0)showExitPopup();});
var lastScrollY=window.scrollY;var scrollUpDist=0;var pageLoad=Date.now();var maxScroll=0;var cachedSH=0;
window.addEventListener('scroll',function(){var cy=window.scrollY;if(cy>maxScroll)maxScroll=cy;if(cy<lastScrollY){scrollUpDist+=(lastScrollY-cy);var tp=(Date.now()-pageLoad)/1000;if(!cachedSH)cachedSH=document.documentElement.scrollHeight;if(scrollUpDist>1200&&cy<150&&tp>30&&maxScroll>cachedSH*0.5){showExitPopup();scrollUpDist=0;}}else{scrollUpDist=0;}lastScrollY=cy;},{passive:true});
exitClose.addEventListener('click',closeExitPopup);exitOverlay.addEventListener('click',closeExitPopup);
/* === Smooth scroll links === */
document.querySelectorAll('a[href^="#"]').forEach(function(l){l.addEventListener('click',function(e){var t=document.querySelector(this.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth',block:'start'});}});});
});